# Generated by Django 5.0.7 on 2024-07-26 11:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.upload_path
            ),
        ),
    ]
